### ISSUE TITLE
Use Require() syntax?

### ISSUE THREAD

**Issue by tylerstillwater** [cheekybits/is#1]
I am wondering if we could move to the "continue by default" approach, and only abort the testing process if a Require is given.

`is.Ok(foo).Require()` would terminate the process, where `is.Ok(foo)` would allow it to proceed to the next test(s)

**Comment by matryer** [comment]
In most cases, people want it to stop if an assertion fails.  And this keeps it simple.

**Comment by tylerstillwater** [comment]
According to the conversation over at testify, it seemed to be the opposite. Continue by default and fail when necessary. Basically, if a subsequent test REQUIRES that an object exist or will panic, then you want to fail at that point, otherwise keep going so you get all the output in one go.

**Comment by matryer** [comment]
What about…

```
is.New(t)
```

```
is.NewStrict(t)
```

Mat
